const GET_LIST_NOTIFY = 'GET_LIST_NOTIFY';
const GET_LIST_NOTIFY_FINISHED = 'GET_LIST_NOTIFY_FINISHED';
const GET_DETAIL_NOTIFY = 'GET_DETAIL_NOTIFY';
const GET_DETAIL_NOTIFY_FINISHED = 'GET_DETAIL_NOTIFY_FINISHED';
const SET_FILTER_INFO = 'SET_FILTER_INFO';

export {
    GET_LIST_NOTIFY, GET_LIST_NOTIFY_FINISHED,
    GET_DETAIL_NOTIFY, GET_DETAIL_NOTIFY_FINISHED,
    SET_FILTER_INFO
}