/**
 * @author: duynn
 * @since: 19/03/2018
 * @description: loại hành động của luồng công việc
 */

const GET_WORKFLOW = 'GET_WORKFLOW';
const GET_WORKFLOW_FINISHED = 'GET_WORKFLOW_FINISHED';

const EXECUTE_WORKFLOW = 'EXECUTE_WORKFLOW';
const EXECUTE_WORKFLOW_FINISHED = 'EXECUTE_WORKFLOW_FINISHED';

const SET_USER_PROCESS = 'SET_USER_PROCESS';
const SET_DEADLINE = 'SET_DEADLINE';
const SET_COMMENT = 'SET_COMMENT';

const REFRESH_WORKFLOW_STATE = 'REFRESH_WORKFLOW_STATE';

const SET_PREVIOUS_NAVIGATOR_STATE = 'SET_PREVIOUS_NAVIGATOR_STATE'

export {
    GET_WORKFLOW, GET_WORKFLOW_FINISHED,
    EXECUTE_WORKFLOW, EXECUTE_WORKFLOW_FINISHED,
    SET_USER_PROCESS, REFRESH_WORKFLOW_STATE, SET_DEADLINE,
    SET_COMMENT, SET_PREVIOUS_NAVIGATOR_STATE
}