# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EbizVNIO' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EbizVNIO
  pod 'Firebase/Messaging'
  target 'EbizVNIO-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EbizVNIOTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EbizVNIO-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EbizVNIO-tvOS

  # target 'EbizVNIO-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
