/**
 * @author: duynn
 * @since: 18/03/2018
 * @description: các loại hành động trong văn bản đến
 */

const GET_LIST_DOCX = 'GET_LIST_DOCX';
const GET_LIST_DOCX_FINISHED = 'GET_LIST_DOCX_FINISHED';

const GET_DETAIL_DOCX = 'GET_DETAIL_DOCX';
const GET_DETAIL_DOCX_FINISHED = 'GET_DETAIL_DOCX_FINISHED';
const SET_DETAIL_DOCX = 'SET_DETAIL_DOCX';

const GET_WORKFLOW_DOCX = 'GET_WORKFLOW_DOCX';
const GET_WORKFLOW_DOCX_FINISHED = 'GET_WORKFLOW_DOCX_FINISHED';

const SET_FILTER_INFO = 'SET_FILTER_INFO';
const RESET_FILTER_VALUE = 'RESET_FILTER_VALUE';

const SET_DOCX_TYPE = 'SET_DOCX_TYPE';

export {
    GET_LIST_DOCX, GET_LIST_DOCX_FINISHED, GET_DETAIL_DOCX, GET_DETAIL_DOCX_FINISHED,
    SET_DETAIL_DOCX, GET_WORKFLOW_DOCX, GET_WORKFLOW_DOCX_FINISHED,
    SET_FILTER_INFO, RESET_FILTER_VALUE, SET_DOCX_TYPE
}