/**
 * @author: duynn
 * @since: 30/03/2018
 * @description: các loại hành động trong văn bản đi
 */
const GET_LIST_DOCX = 'GET_LIST_DOCX';
const GET_LIST_DOCX_FINISHED = 'GET_LIST_DOCX_FINISHED';

const GET_DETAIL_DOCX = 'GET_DETAIL_DOCX';
const GET_DETAIL_DOCX_FINISHED = 'GET_DETAIL_DOCX_FINISHED';
const SET_DETAIL_DOCX = 'SET_DETAIL_DOCX';

const SET_DOCX_TYPE = 'SET_DOCX_TYPE';
const SET_FILTER_INFO = 'SET_FILTER_INFO';

export {
    GET_LIST_DOCX, GET_LIST_DOCX_FINISHED, GET_DETAIL_DOCX, 
    GET_DETAIL_DOCX_FINISHED, SET_DETAIL_DOCX, SET_DOCX_TYPE,
    SET_FILTER_INFO
}